- type: job
  id: ACFighter
  name: class-name-fighter
  description: class-description-fighter
  playTimeTracker: ACFighter
  startingGear: ACFighterGear
  icon: "ACClassIconFighter"
  special:
  - !type:AddComponentSpecial
    components:
    - type: Stats
      initialStats:
        Strength: 11
        Dexterity: 8
        Vigor: 10
        Intelligence: 1

- type: job
  id: ACRanger
  name: class-name-ranger
  description: class-description-ranger
  playTimeTracker: ACRanger
  startingGear: ACRangerGear
  icon: "ACClassIconRanger"
  special:
  - !type:AddComponentSpecial
    components:
    - type: Stats
      initialStats:
        Strength: 9
        Dexterity: 12
        Vigor: 8
        Intelligence: 1

- type: job
  id: ACRogue
  name: class-name-rogue
  description: class-description-rogue
  playTimeTracker: ACRogue
  startingGear: ACRogueGear
  icon: "ACClassIconRogue"
  special:
  - !type:AddComponentSpecial
    components:
    - type: Stats
      initialStats:
        Strength: 7
        Dexterity: 11
        Vigor: 6
        Intelligence: 6

- type: job
  id: ACWizard
  name: class-name-wizard
  description: class-description-wizard
  playTimeTracker: ACWizard
  startingGear: ACWizardGear
  icon: "ACClassIconWizard"
  special:
  - !type:AddComponentSpecial
    components:
    - type: Stats
      initialStats:
        Strength: 4
        Dexterity: 7
        Vigor: 5
        Intelligence: 14
