- type: dungeonConfig
  id: ACStone
  generator: !type:PrefabDunGen
    roomWhitelist:
      - ACStoneDungeon
    presets:
    - ACCompact
  postGeneration:

    - !type:RoomEntrancePostGen
      tile: ACFloorStoneDungeon3
      entities:
        - ACDoorWood

    - !type:ACLimitedEntityPostGen
      entity: ACStairsUp

    - !type:ACLimitedEntityPostGen
      entity: ACStairsDown

    - !type:CorridorPostGen
      corridorTile: ACFloorStoneDungeon3
      width: 1

    - !type:JunctionPostGen
      width: 1
      entities:
        - ACDoorWood

    - !type:BoundaryWallPostGen
      tile: ACFloorStoneDungeon3
      wall: ACWallDungeon
      cornerWall: ACWallDungeon
